name: Dockerfile Lint

on:
  pull_request:
    paths:
      - Dockerfile
      - docker-compose.yml
      - .github/workflows/dockerfile-lint.yml
  push:
    branches:
      - master
      - main
      - develop
      - feature/*
      - hotfix/*
      - release/*

jobs:
  lint:
    name: Dockerfile Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Hadolint
        id: hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Update Pull Request
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          script: |
            const output = `
            #### 🔍 Dockerfile Lint Results
            
            **Status:** \`${{ steps.hadolint.outcome }}\`
            
            <details>
            <summary>Detailed Results</summary>
            
            \`\`\`
            ${process.env.HADOLINT_RESULTS}
            \`\`\`
            </details>
            `;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
